disp('Set up a new Diophantine problem')
b=RR_poly([-2 2 -5 5],1), a=RR_poly([-1 1 -3 3 -6 6],1)
f=RR_poly([-1 -1 -3 -3 -6 -6 -20],1)
[x,y] = RR_diophantine(a,b,f), test=trim(a*x+b*y), residual1=norm(f-test)
fprintf('Note that the solution {x,y} is proper (x.n=y.n), and solves a*x+b*y=f with ~ zero residual\n\n')
